package concurrent.locks;

import org.junit.Test;

import static org.junit.Assert.*;

/**
 * Skip test, because ReentrantReaderWriteUpdateLock generated by other.
 * @see "https://github.com/npgall/concurrent-locks"
 */
public class ReentrantReadWriteUpdateLockTest {
    @Test
    public void updateLock() throws Exception {
    }

    @Test
    public void readLock() throws Exception {
    }

    @Test
    public void writeLock() throws Exception {
    }

}